//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC.ServiceAseguradora {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Result", Namespace="http://schemas.datacontract.org/2004/07/SL_WCF")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ModelLayer.Aseguradora))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ModelLayer.Usuario))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ModelLayer.Direccion))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ModelLayer.Colonia))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ModelLayer.Municipio))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ModelLayer.Estado))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ModelLayer.Pais))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ModelLayer.Rol))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(ModelLayer.Result))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(object[]))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(System.Exception))]
    public partial class Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool CorrectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Exception ExeptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object ObjectField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private object[] ObjectsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Correct {
            get {
                return this.CorrectField;
            }
            set {
                if ((this.CorrectField.Equals(value) != true)) {
                    this.CorrectField = value;
                    this.RaisePropertyChanged("Correct");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Exception Exeption {
            get {
                return this.ExeptionField;
            }
            set {
                if ((object.ReferenceEquals(this.ExeptionField, value) != true)) {
                    this.ExeptionField = value;
                    this.RaisePropertyChanged("Exeption");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object Object {
            get {
                return this.ObjectField;
            }
            set {
                if ((object.ReferenceEquals(this.ObjectField, value) != true)) {
                    this.ObjectField = value;
                    this.RaisePropertyChanged("Object");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public object[] Objects {
            get {
                return this.ObjectsField;
            }
            set {
                if ((object.ReferenceEquals(this.ObjectsField, value) != true)) {
                    this.ObjectsField = value;
                    this.RaisePropertyChanged("Objects");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceAseguradora.IAseguradora")]
    public interface IAseguradora {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAseguradora/GetAll", ReplyAction="http://tempuri.org/IAseguradora/GetAllResponse")]
        MVC.ServiceAseguradora.Result GetAll();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAseguradora/GetAll", ReplyAction="http://tempuri.org/IAseguradora/GetAllResponse")]
        System.Threading.Tasks.Task<MVC.ServiceAseguradora.Result> GetAllAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAseguradora/GetById", ReplyAction="http://tempuri.org/IAseguradora/GetByIdResponse")]
        MVC.ServiceAseguradora.Result GetById(int IdAseguradora);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAseguradora/GetById", ReplyAction="http://tempuri.org/IAseguradora/GetByIdResponse")]
        System.Threading.Tasks.Task<MVC.ServiceAseguradora.Result> GetByIdAsync(int IdAseguradora);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAseguradora/Add", ReplyAction="http://tempuri.org/IAseguradora/AddResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ModelLayer.Usuario))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ModelLayer.Direccion))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ModelLayer.Colonia))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ModelLayer.Municipio))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ModelLayer.Estado))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ModelLayer.Pais))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ModelLayer.Rol))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ModelLayer.Result))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Exception))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MVC.ServiceAseguradora.Result))]
        MVC.ServiceAseguradora.Result Add(ModelLayer.Aseguradora aseguradora);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAseguradora/Add", ReplyAction="http://tempuri.org/IAseguradora/AddResponse")]
        System.Threading.Tasks.Task<MVC.ServiceAseguradora.Result> AddAsync(ModelLayer.Aseguradora aseguradora);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAseguradora/Update", ReplyAction="http://tempuri.org/IAseguradora/UpdateResponse")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ModelLayer.Usuario))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ModelLayer.Direccion))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ModelLayer.Colonia))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ModelLayer.Municipio))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ModelLayer.Estado))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ModelLayer.Pais))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ModelLayer.Rol))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(ModelLayer.Result))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(object[]))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(System.Exception))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(MVC.ServiceAseguradora.Result))]
        MVC.ServiceAseguradora.Result Update(ModelLayer.Aseguradora aseguradora);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAseguradora/Update", ReplyAction="http://tempuri.org/IAseguradora/UpdateResponse")]
        System.Threading.Tasks.Task<MVC.ServiceAseguradora.Result> UpdateAsync(ModelLayer.Aseguradora aseguradora);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAseguradora/Delete", ReplyAction="http://tempuri.org/IAseguradora/DeleteResponse")]
        MVC.ServiceAseguradora.Result Delete(int IdAseguradora);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAseguradora/Delete", ReplyAction="http://tempuri.org/IAseguradora/DeleteResponse")]
        System.Threading.Tasks.Task<MVC.ServiceAseguradora.Result> DeleteAsync(int IdAseguradora);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAseguradoraChannel : MVC.ServiceAseguradora.IAseguradora, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AseguradoraClient : System.ServiceModel.ClientBase<MVC.ServiceAseguradora.IAseguradora>, MVC.ServiceAseguradora.IAseguradora {
        
        public AseguradoraClient() {
        }
        
        public AseguradoraClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AseguradoraClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AseguradoraClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AseguradoraClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public MVC.ServiceAseguradora.Result GetAll() {
            return base.Channel.GetAll();
        }
        
        public System.Threading.Tasks.Task<MVC.ServiceAseguradora.Result> GetAllAsync() {
            return base.Channel.GetAllAsync();
        }
        
        public MVC.ServiceAseguradora.Result GetById(int IdAseguradora) {
            return base.Channel.GetById(IdAseguradora);
        }
        
        public System.Threading.Tasks.Task<MVC.ServiceAseguradora.Result> GetByIdAsync(int IdAseguradora) {
            return base.Channel.GetByIdAsync(IdAseguradora);
        }
        
        public MVC.ServiceAseguradora.Result Add(ModelLayer.Aseguradora aseguradora) {
            return base.Channel.Add(aseguradora);
        }
        
        public System.Threading.Tasks.Task<MVC.ServiceAseguradora.Result> AddAsync(ModelLayer.Aseguradora aseguradora) {
            return base.Channel.AddAsync(aseguradora);
        }
        
        public MVC.ServiceAseguradora.Result Update(ModelLayer.Aseguradora aseguradora) {
            return base.Channel.Update(aseguradora);
        }
        
        public System.Threading.Tasks.Task<MVC.ServiceAseguradora.Result> UpdateAsync(ModelLayer.Aseguradora aseguradora) {
            return base.Channel.UpdateAsync(aseguradora);
        }
        
        public MVC.ServiceAseguradora.Result Delete(int IdAseguradora) {
            return base.Channel.Delete(IdAseguradora);
        }
        
        public System.Threading.Tasks.Task<MVC.ServiceAseguradora.Result> DeleteAsync(int IdAseguradora) {
            return base.Channel.DeleteAsync(IdAseguradora);
        }
    }
}
